spring.application.name=Bandsync

spring.datasource.url=jdbc:postgresql://ep-restless-morning-atbvac73-pooler.c-9.us-east-1.aws.neon.tech/BandSync_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zdw9HEc5MiPf
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect